site_name: FastAPI Sessions
site_description: Ready-to-use session authentication for FastAPI

theme:
    name: 'material'

repo_name: jordanisaacs/fastapi-sessions
repo_url: https://github.com/jordanisaacs/fastapi-sessions
edit_uri: ""

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.tasklist
  - pymdownx.superfences
  - admonition

nav:
  - About: index.md
  - Sessions: sessions.md
  - Guide:
    - Getting Started: guide/getting_started.md